version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
