name: Fence CI/CD Pipeline

# Define when the workflow should run
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

# Define global environment variables
env:
  PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
  POETRY_CACHE_DIR: ${{ github.workspace }}/.cache/poetry
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Secrets are stored in GitHub Secrets

# Define jobs to run in the workflow
jobs:
  # Job for running tests
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Activate virtual environment
        run: source `poetry env info --path`/bin/activate

      - name: Run tests
        run: |
          cd tests
          python3 -m pytest --junitxml=report.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/report.xml

  # Job for building the package
  build:
    runs-on: ubuntu-latest
    needs: test # Only run if the test job passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build the package
        run: poetry build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
          retention-days: 7

  # Job for publishing the package
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build the package
        run: poetry build

      - name: Publish to GitHub Packages
        run: |
          poetry config repositories.github "https://pypi.pkg.github.com/${{ github.repository_owner }}"
          poetry publish --repository github -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
